### PR TITLE
feat: add typescript support

### PR DESCRIPTION
**Pull request by cachho**
rewrote the whole package in typescript.

sucessfully tested against the javascript example in a javascript file.

### CODE REVIEW

**Comment by justingrant** [comment]
Amazing!  I was just hunting for a @types/embedchain. Hopefully @taranjeet is OK with TS. It'd be quite helpful to have TS support.

**Comment by cachho** [comment]
> Amazing! I was just hunting for a @types/embedchain. Hopefully @taranjeet is OK with TS. It'd be quite helpful to have TS support.

yeah I think it's going to greatly improve the dev experience and allow us to iterate quicker.

**Comment by taranjeet** [comment]
looks good @cachho

**Comment by justingrant** [comment]
Would it be possible to push a new release to npm including this PR? I can always build locally in the meantime, but deploying to "prod" (not really production, just a hosted playground) would be easier. Thanks!

**Comment by taranjeet** [comment]
hey @justingrant , npm release is planned for today. 
Join our discord to stay updated: https://discord.com/invite/6PzXDgEjG5

**Pull request merged**
